apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-project
spec:
  replicas: 4
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  selector:
    matchLabels:
      app: eks-project
  template:
    metadata:
      labels:
        app: eks-project
    spec:
      restartPolicy: Always
      containers:
        - name: springboot 
          image: 014610777298.dkr.ecr.us-east-1.amazonaws.com/eks-project:eks-project-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: eks-project
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: eks-project
